[phases.setup]
nixPkgs = ['nginx', 'php82', 'php82Extensions.pdo', 'php82Extensions.pdo_pgsql', 'php82Extensions.mbstring', 'php82Extensions.zip', 'php82Extensions.gd', 'php82Extensions.bcmath', 'php82Extensions.exif', 'php82Extensions.pcntl', 'php82Extensions.opcache']

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader --no-interaction']

[phases.build]
cmds = [
  'php artisan config:cache || true',
  'php artisan route:cache || true'
]

[start]
cmd = './start.sh'